### ISSUE TITLE
Custom calendar images are missing

### ISSUE THREAD

**Issue by andrewbranch** [fumc-pensacola/transept#59]
Looks like they never made it back from when we moved the database. @JebHunt if you have time to help fix this, go to https://console.aws.amazon.com/s3/home?region=us-west-2#&bucket=fumcappfiles (you'll have to remember your login) and comment here with a mapping of the calendar name as it appears in the app and the photo's filename that you find in the bucket. E.g.

>Methodist Children's Academy: MCA.jpg
>Music and Worship Arts: MusicAndStuffOrWhatever.jpg

**Comment by JebHunt** [comment]
Children’s Ministries: Children.jpg

50 Forward: 50_Forward.jpg

Christian Education: Christian_Education.jpg

Funerals: Funerals.jpg

Methodist Children’s Academy: MCA.jpg

Men’s Ministries: Men.jpg

Mission and Outreach: MissionandOutreach.jpg

Music Ministry: Music_WorshipArts.jpg

Community Events: Pensacola_Events.jpg

Kitchen Ministry: Ruths_Kitchen.jpg

Tween Ministries: Tween_Ministries.jpg

Weddings: Weddings.jpg

Women’s Ministries: Women.jpg

Youth Ministries: Youth_Ministries.jpg

Scouting Ministries: scouting.jpg

**Comment by andrewbranch** [comment]
@JebHunt you’re a real gem

**Comment by andrewbranch** [comment]
Fixed
